# Generated by Django 6.0.7 on 2026-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0005_postanalysis_delete_postaibreakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="fwd_from",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name="ID канала-источника репоста",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="mentions",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Упоминания каналов"
            ),
        ),
    ]
