# Generated by Django 6.0.6 on 2026-08-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Используется в URL статьи.",
                        max_length=220,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Краткое описание для карточки статьи.",
                        verbose_name="Анонс",
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True,
                        help_text="URL изображения обложки.",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown или rich text.",
                        verbose_name="Текст статьи",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Маркетинг"),
                            ("telegram", "Telegram"),
                            ("ai", "ИИ и автоматизация"),
                            ("product", "Продукт"),
                            ("news", "Новости"),
                        ],
                        default="marketing",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список строк-тегов.",
                        verbose_name="Теги",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="В избранном"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Опубликована"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "read_time",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Время чтения (мин)"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Просмотры"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создана"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлена"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Статьи блога",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "is_featured"],
                        name="blog_blogar_is_publ_9fb14f_idx",
                    )
                ],
            },
        ),
    ]
