# Generated by Django 6.0.6 on 2026-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("marketing", "Маркетинг"),
                    ("telegram", "Telegram"),
                    ("ai", "ИИ и автоматизация"),
                    ("product", "Продукт"),
                    ("dev", "Разработка"),
                    ("news", "Новости"),
                ],
                default="marketing",
                max_length=50,
                verbose_name="Категория",
            ),
        ),
    ]
