# Generated by Django 5.2.4 on 2025-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_channels', '0001_initial'),
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='groups', to='parser.telegramchannel', verbose_name='Каналы'),
        ),
    ]
